### ISSUE TITLE
/f claim a gets CommandSender error (Forge Support Request)

### ISSUE THREAD

**Issue by BlayzerQ** [MassiveCraft/Factions#940]
When i tried /f claim, i get "Error: Your "commandsender link" has been severed"
How fix it?
![b126e39f](https://cloud.githubusercontent.com/assets/10747701/9997195/85ed4ca6-6093-11e5-96c5-2e16c248144f.png)
![252847fe](https://cloud.githubusercontent.com/assets/10747701/9997210/97559dd6-6093-11e5-9e21-8675ae00c9d2.png)
![dac93e92](https://cloud.githubusercontent.com/assets/10747701/9997217/a666c1ba-6093-11e5-91f7-687be3bde966.png)

**Comment by BlayzerQ** [comment]
KCauldron https://gitlab.prok.pw/Prototik/KCauldron

**Comment by MarkehMe** [comment]
I'm not sure KCauldron is supported, @oloflarsson or @magnusulf may be able to help you better here. 

Please attach your server error logs as well.

**Comment by ulumulu1510** [comment]
This is a known issue. Last stances was: we do not support Cauldron because it is dead. Some Class s missing/changed in cauldron and thus cannot be accessed.

**Comment by BlayzerQ** [comment]
KCauldron is live, its not Cauldron!
Please add support KCauldron!

**Comment by MarkehMe** [comment]
Until we can see stack traces or error logs we won't be able to do much!

**Comment by BlayzerQ** [comment]
[22:05:00] [Server thread/WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PlayerInventory
[22:05:00] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[22:05:00] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.massivecore.particleeffect.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:414)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.massivecore.mixin.InventoryMixinDefault.<clinit>(InventoryMixinDefault.java:35)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.massivecore.mixin.Mixin.<clinit>(Mixin.java:35)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.SenderEntity.isOffline(SenderEntity.java:97)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.SenderColl$2.apply(SenderColl.java:142)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.SenderColl$2.apply(SenderColl.java:139)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.MStoreUtil.uglySQL(MStoreUtil.java:25)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.Coll.getAll(Coll.java:141)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.SenderColl.getAllOffline(SenderColl.java:138)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.factions.entity.MPlayerColl.considerRemovePlayerMillis(MPlayerColl.java:53)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.factions.task.TaskPlayerDataRemove.invoke(TaskPlayerDataRemove.java:36)
[22:05:00] [Server thread/WARN]: 	at com.massivecraft.massivecore.ModuloRepeatTask.run(ModuloRepeatTask.java:76)
[22:05:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[22:05:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[22:05:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:873)
[22:05:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[22:05:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[22:05:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[22:05:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by MarkehMe** [comment]
What is your version of MassiveCore and Factions?

**Comment by BlayzerQ** [comment]
Last versions.

**Comment by KTRD** [comment]
I'm getting same. when I do /f claim.
![2015-09-23_13 37 17](https://cloud.githubusercontent.com/assets/14803896/10045149/5eebbf6e-61f8-11e5-92c9-713c6046674d.png)

oh it does work after you do /f admin.
I'm using Kcauldron 1.7.10-1492.155.
the 3 plugins that are in are 
PermissionBukkit-2-4
MassiveCore 2.8.0
Factions 2.8.0
I get no error logs :(

I am think is the same problem as BlayzerQ and I dount want to open another issue witch looks same as this one.

and one more if you need more info just ask and I try and get it if I can.

**Comment by coolmodi** [comment]
For me it works fine for some time when i wipe the world and/or pluginsettings, i can claim land without a problem, but when i try it sometimes later or the next day, i will get that error. With admin mode active it will still work though.

So it's not that there is something missing or not working at all, but it rather stops working for some reason i can't figure out.

KCauldron build 1492.150, factions 2.8.1.

**Comment by Coolaxer** [comment]
I would like to add some extra information on this issue.
On a fresh startup (no exisitng files) it works perfectly. However, on the next restart, any existing factions or players from before are completely broken. New players are still able to play and use commands. This is an issue with Factions 2.7.5&up. I do not think this is an issue with missing class files, because if we reset the faction files for those old players, they can claim and use commands till the next restart. From my observation, this has something to do with cauldron saving the data improperly. (Do note, cauldron has all the class files from bukkit, its the forge files that are manipulated)

**Comment by Gakido62** [comment]
Hello you talk about class missing or changed but can you tell us more about that please ? I am not expert but i am developper and if you have any idea from code where is the problem, i can try to help for fix it.
I test several Faction version in 2.7.4 with cauldron, after restart the plugin doesn't take the config and all player can claim like admin mod.
In 2.8.1 after restart nobody can claim and it's juste say "ERROR: Your CommandSender Link has been severed."
In both cases there is no error in the server logs.

**Comment by magnusulf** [comment]
Cauldron (and KCauldron) is not supported. It is unlikely that we will add Cauldron support in the future. If however you can add Cauldron support, feel free to make a PR.

**Comment by MarkehMe** [comment]
Some advice would be to disable all other KCauldron/Cauldron mods and see if that fixes the issue.

**Comment by DraksterAU** [comment]
@MarkehMe Unfortunately not.. Cauldron + Factions only fails. Its a shame, some of Massivecrafts best work has gone into more recent releases.

**Comment by MarkehMe** [comment]
@DraksterAU The issue is the particleeffect library. 

You can see the chatter here: https://github.com/MassiveCraft/MassiveCore/issues/200

If I have time I will look into it. However it should be a case of working out where the PlayerInventory class is.

**Comment by DraksterAU** [comment]
Omg man!!!!!!

If you guys can fix this I'm happy to shout you some beers ;-) 

On behalf of all Cauldron/ Kcauldron (Cauldron under a new) users we appreciate your time :-)

**Comment by ChrisLane** [comment]
Reverting 6ab443c8b769e58196f07e101e7560093251fa43 and c1db14eebef7dff790f6c6364184796a243e126a
fixes the issue with claiming and unclaiming not working on KCauldron, this does obviously also allow anyone to claim/unclaim any land without permission again.

Would it be possible to fix the issue that these commits targeted in a different way in order to fix this issue with KCauldron?

After undoing these commits, I only receive a console error (http://paste2.org/3hczLgh7) and everything appears normal to the player (besides being able to claim/unclaim land they shouldn't).

**Comment by MarkehMe** [comment]
I'm assuming you mean reverting back to the builds at that time. I already know the issue, however if you can find out where they've refracted PlayerInventory to I'll be able to implement a fix. 

I am hunting for it in my own time but if you can look for it too, that would be great.

**Comment by DraksterAU** [comment]
Hi Mark, is this not two seperate issues?

1: The console spammed error about inventory
2: The lack of being able to claim?

I only say this as I have had one issue (claims) without the other on 2.7.4-5... But that might have been luck.

He is right about the claim one being fixed with a commit revert, I've tested it

**Comment by ChrisLane** [comment]
Personally, I didn't revert to the builds that existed at the time, I reverted the changes in those commits so that everything else is still the latest version.

I'll see if I can find where PlayerInventory's moved to but I doubt my chances there.

**Comment by ChrisLane** [comment]
Just checked my logs from my most recent testing and I don't actually have a missing class exception for PlayerInventory, only PacketPlayOutWorldParticles.

http://paste2.org/25VjUMpc

**Comment by MarkehMe** [comment]
Yep.. so the issue is that it can't find the classes PlayerInventory and PacketPlayOutWorldParticles, because when KCauldron does whatever it does.. it throws them somewhere (I don't know where either)

**Comment by Robotia** [comment]
@MarkehMe @BlayzerQ @CoolaxGaming @coolmodi @Gakido62 
I have fixed this in the official TCPR fixes repository. See here: https://github.com/TCPR/Fixes

**Comment by MarkehMe** [comment]
@Robotia this doesn't fix the issue

**Comment by DraksterAU** [comment]
Hi @markehme,

Actually his factions build does work on my server - we haven't noticed any bugs (except the duplicate message one) since installing it.

I did notice occasionally the error for massive core comes up on startup though....

Regards

@DraksterAU

**Comment by Robotia** [comment]
@MarkehMe Are you certain? It is working perfectly for me with Thermos.

**Comment by MarkehMe** [comment]
It works, but it does not solve the issue. It's a work around for sure though. Not a healthy solution.

I am going to get my local repos up to date and solve this myself now. :)

**Comment by Robotia** [comment]
@MarkehMe That is a known, cross-plugin problem with CraftBukkit Forge servers, I did not intend to create compatibility for that. The goal was to simply make the latest version of Factions usable.
If you find a good solution, please share

**Comment by MarkehMe** [comment]
Ok so I just tried this on my own server, connected with a Forge 1.7 client and using KCauldron version 1.7.10-1614.188.

I cannot replicate the issue. It claimed fine? Unless something was changed in MassiveCore or Factions in the latest source to fix it. 

The ParticleEffect error will show as it's an outdated version of Bukkit, however it is not game-breaking. Maybe we should add detection for this and not call this. 

Can you please walk through exactly as is, on at least KCauldron 1.7.10-1614.188

**Comment by DraksterAU** [comment]
The issue is after a server restart that you are not able to claim territory. Did you make sure to shut down and restart the server after you'd logged in and claimed some territory @MarkehMe ?

**Comment by MarkehMe** [comment]
I've replicated the problem and have found the issue. :)

**Comment by DraksterAU** [comment]
Woot! :dancers: 

If you could fix the duplicate Territory entry message while you're at it................ (Not being a dick, its the only other KCauldron specific bug haha)

**Comment by DraksterAU** [comment]
@MarkehMe Is this going to be part of MassiveCraft's factions, or a patch applied with FP?

**Comment by MarkehMe** [comment]
For some reason, after fixing this issue that  bug does not come up.. doing some further testing on this now. 

As you can see here: https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/store/SenderEntity.java#L30-L34

For whatever reason ```sender``` is sometimes null under KCauldron.

I've created a fix / extra check, here: https://github.com/MarkehMe/MassiveCore/commit/2fb8a7009b6aa9e163e043eba67358618acfd5f1

**Comment by DraksterAU** [comment]
Wow, that simple @MarkehMe ? WOW!

**Comment by DraksterAU** [comment]
@magnusulf You think you might be interested in this fix?

**Comment by ulumulu1510** [comment]
Have you tested this to work Markehme? :) Can you figure out why it gets set to null? Can that be dogded eventually?

**Comment by Robotia** [comment]
Returning a null sender is a bad idea...you'll introduce a host of null exceptions. Instead, it might be a good idea to see what sets the value for command sender and modify that.

**Comment by DraksterAU** [comment]
That would be a KCauldron thing though, yes?
The official KCauldron guys have turned down investigating this. Marks idea would probably be the best workaround?

**Comment by ulumulu1510** [comment]
@Robotia & @DraksterAU , Markehme is making further investigations later this day. We are still unsure to why the field initially gets set to null, but he is pointing it down more and more.

**Comment by Robotia** [comment]
@ulumulu1510 
It is a good workaround, but what is very strange is the fact that it is null. Either the act of initiateSender() is setting a null value or the InternalListener is changing it to null. :confused:

**Comment by DraksterAU** [comment]
@ulumulu1510 No worries :) Just putting my 2 cents in haha.

**Comment by ulumulu1510** [comment]
@Robotia :
One thing I just don't understand is, why do you now care about the correct implementation? Because if you would have cared about this before we might would have fixed this earlier.

According to markehme initiateSender() wasn't called at first when running with KCauldron and then runs into a loop that doesn't happen with Spigot. He is investigating what actually causes the issue, which is the right thing to do. Feel free to help us out on the investigation, so we can fix it once and for all in the right place.

**Comment by Robotia** [comment]
ParticleLib won't be easy to fix since it's directly calling getClass(). Calls to getClass cannot be modified by KCauldron (or any other Java program as far as I am aware of) to fit the CraftBukkit Forge method/field format.
What *might* work is adding the mappings for `cb2num.pkg` into the ParticleLib package and mapping the string for the class & package before it gets sent to getClass().

@ulumulu1510 I only recently got really involved and several people have mentioned it to me in relation to https://github.com/TCPR/Thermos, an optimized fork of KCauldron. If @MarkehMe identifies the cause I would be glad to implement it.

**Comment by DraksterAU** [comment]
@robotia Your 2.8.5 build seems to think all interactions (right click on computers specifically) require build perms in a faction..... Just noticed now because people cant use computers in safezones or warzones anymore .... :/

**Comment by Robotia** [comment]
@DraksterAU That was to solve an issue where blocks like ProjectE's condensers could be accessed in a player's claim without the player's explicit permission, interaction events had to be considered for every block. I can try to create a build where this is not included if you would like.

**Comment by DraksterAU** [comment]
@Robotia Wouldn't you be better creating a custom interact permission node?

**Comment by magnusulf** [comment]
You can add block types to "materialsContainer" in the config to make them be seen as containers by the plugin. There is aslo a few similar configurations where you can add other custom blocks.

**Comment by DraksterAU** [comment]
Oooh, so the whole change that was made to mess up interacts is moot... we just use that =D

**Comment by DraksterAU** [comment]
@magnusulf Thanks for your help, but I've decided to use @markeheme's fix with your official 2.8.5 build to enable KCauldron support, bypassing the need for the custom factions one from Robo.

I (and many many others) would love to see you implement that in the official build if it is possible!!!! :)

**Comment by magnusulf** [comment]
@DraksterAU what MarkehMe did was a sympton fix, not a solution to the actual problem, furthermore this symptom fix will slow down some of our other plugins, which is why would would like an actual solution.

**Comment by DraksterAU** [comment]
Ah, Ok, I didn't realise that would be such a performance hit.. sorry! :)

**Comment by DraksterAU** [comment]
No worries @magnusulf .... keen as you can imagine ;)

**Comment by MarkehMe** [comment]
Found the issue ...

```EngineMassiveCoreDatabase#setSenderReferences``` is called, which does an isOnline check here:

https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/engine/EngineMassiveCoreDatabase.java#L86

Turns out, ```player#isOnline``` is returning false. Therefore, the reference is set to null. As the player isn't online in KCauldron at this point.. leading to another ```setSenderReferences``` being called.. with a null sender.  In this, we set the sender initiated to true (we shouldn't be doing this, as the sender isn't initiated) .

Submitted the fix for feedback. https://github.com/MarkehMe/MassiveCore/commit/3c313360b6686714d32b9cc3e956581385122dbe

**Comment by MarkehMe** [comment]
After discussion with Cay we decided its a pretty unhealthy solution.

This issue comes from sending the initial reference. It's setting null when checking if the player is online (the reference is set to null if the player is offline) see here: https://github.com/MassiveCraft/MassiveCore/blob/14ad78ef1587c89527c0dd891e0b5c852c86f4fb/src/com/massivecraft/massivecore/engine/EngineMassiveCoreDatabase.java#L83-L101

Because with KCauldron/Cauldron there can be any number of mods it could take anywhere from 3s, 5s, even 20s until all the mods have been loaded and the player is than counted as online. So checking a tick later is not a viable solution. 

Thats why I suggest a later check when we're 100% the player is online in the game (by checking with basic events). 

My solution (tested and working):

Run a Cauldron check here: https://github.com/MarkehMe/MassiveCore/blob/dcfb45ab232af8af219b3846caa65c2209227cfb/src/com/massivecraft/massivecore/engine/EngineMassiveCoreDatabase.java#L93-L97

Then set the reference later: https://github.com/MarkehMe/MassiveCore/blob/dcfb45ab232af8af219b3846caa65c2209227cfb/src/com/massivecraft/massivecore/engine/EngineMassiveCoreCauldron.java#L61-L88

Heres the full commit: https://github.com/MarkehMe/MassiveCore/commit/dcfb45ab232af8af219b3846caa65c2209227cfb

**Comment by DraksterAU** [comment]
Do you think this fix will be implemented guys?

**Comment by MarkehMe** [comment]
My solution simply sets the sender references later (after the player is logged in), however there has been discussions about changing how the sender references are set. However, I've not got much feedback lately on this as the MassiveCraft team is busy with some other projects. :disappointed: 

I will for now quickly make this into a quick-fix plugin for you/everyone to use until that is done

**Comment by DraksterAU** [comment]
@MarkehMe Much appreciated man. I already compiled your fork tho but others will definitely benefit!

**Comment by MarkehMe** [comment]
I have released the source code and such here:

https://github.com/MarkehMe/MassiveCoreForgeFixes

You can download the fix plugin here:

https://github.com/MarkehMe/MassiveCoreForgeFixes/releases/tag/v1.0.0

**Comment by MarkehMe** [comment]
Fixed in https://github.com/MassiveCraft/MassiveCore/commit/76e7702d2fda947bd70e53c5ee99b929d0a2c791 and https://github.com/MassiveCraft/MassiveCore/commit/30a4c20822fa83b4f2094eaa83bffb68e7d97405

🎉 🎈

**Comment by DraksterAU** [comment]
Well done Markehme!

**Comment by Andrew2070** [comment]
Quick question, does this mean in the Factions m_conf instance.json file, under the materialsContainers: tab, i can list modded items like for example MOD:BLOCKNAME
or do they have to be listed as MOD_BLOCKNAME?

Can someone tell me the correct format if this works?
I have also installed the forge fix plugin.

**Comment by MarkehMe** [comment]
This issue exists in newer versions of MassiveCore sadly so i'll reopen the issue 😞  

Not sure if the Forge Fixes plugin still works - but I don't think it has any breaking changes. 

Modded blocks won't work because they need to be in the Bukkit enum 'Material'.

**Comment by Bysokar** [comment]
Mark they are in the material enum, they are added on server start.
Mcff doesnt work with newer versions.

**Comment by MarkehMe** [comment]
Oh damn :( I'll take some time to fix it up this week.

So as long as it can be found in the Material enum it will work :)

**Comment by Bysokar** [comment]
Yeah containers work - modded ones too. Just need to check server log for the material name that was loaded on server start.

Issue is more wrenches dont throw an interact event (i think they have their own wrench event in forge) so to support that you will need to have a list of items you cant have in your hand when interacting with blocks and items in a territory you dont have build perms... or create a listener for that wrench event which I doubt you'd do in a bukkit plugin.

**Comment by Bysokar** [comment]
Mcff doesnt work  because the factions plugin doesnt load on cauldron anymore last time i checked.
Mcff would probably still work if it did.

**Comment by MarkehMe** [comment]
I'll have to look and see if I can create a quick fix plugin for it, but it may be a NMS issue

**Comment by Bysokar** [comment]
It is. The errors related to mc classes missing

**Comment by oloflarsson** [comment]
I'm afraid I'll now close this issue. Thermos/KCauldron is abandoned by it's authors and only ~3% of servers run it (https://bstats.org/global/bukkit). That does not mean I'm agains supporting Thermos/KCauldron. Feel free to code a pull request adding support at any time.
